# Generated by Django 6.1.1 on 2026-10-06 12:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("station", "Station"),
                            ("structure", "Structure"),
                            ("solar_system", "Solar System"),
                            ("unknown", "Unknown"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("solar_system_id", models.IntegerField(null=True)),
                ("type_id", models.IntegerField(null=True)),
                ("owner_id", models.IntegerField(null=True)),
                ("resolved", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=40)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ok", "Ok"),
                            ("error", "Error"),
                            ("missing_scopes", "Missing Scopes"),
                            ("token_invalid", "Token Invalid"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=300)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                (
                    "next_due",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("failures", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_statuses",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "sync statuses",
                "permissions": [
                    ("view_all_characters", "Can view every member's character data"),
                    (
                        "view_alliance_characters",
                        "Can view character data of their alliance",
                    ),
                    (
                        "view_corporation_characters",
                        "Can view character data of their corporation",
                    ),
                ],
                "unique_together": {("character", "section")},
            },
        ),
    ]
