# Generated by Django 6.1.2 on 2026-10-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sheet", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="syncstatus",
            options={
                "permissions": [
                    ("view_all_characters", "Can view every member's character data"),
                    (
                        "view_alliance_characters",
                        "Can view character data of their alliance",
                    ),
                    (
                        "view_corporation_characters",
                        "Can view character data of their corporation",
                    ),
                    (
                        "refresh_characters",
                        "Can refresh character data from ESI now (characters they can view)",
                    ),
                ],
                "verbose_name_plural": "sync statuses",
            },
        ),
    ]
