# Generated by Django 6.1.1 on 2026-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0001_initial"),
        ("accounts", "0001_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("eve", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="state",
            name="member_characters",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="accounts.character"
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="member_corporations",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="eve.evecorporation"
            ),
        ),
        migrations.AddField(
            model_name="state",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="+", to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="allowed_states",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to allow every state",
                related_name="groups",
                to="access.state",
            ),
        ),
    ]
