# Generated by Django 6.1.1 on 2026-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField()),
                ("type_id", models.IntegerField(db_index=True)),
                ("location_id", models.BigIntegerField()),
                ("root_location_id", models.BigIntegerField()),
                ("location_flag", models.CharField(max_length=60)),
                ("quantity", models.IntegerField()),
                ("runs", models.IntegerField()),
                ("material_efficiency", models.SmallIntegerField()),
                ("time_efficiency", models.SmallIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blueprints",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "item_id")},
            },
        ),
    ]
