# Generated by Django 6.1.1 on 2026-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MiningEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("solar_system_id", models.IntegerField()),
                ("type_id", models.IntegerField()),
                ("quantity", models.BigIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mining",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {
                    ("character", "date", "solar_system_id", "type_id")
                },
            },
        ),
    ]
