# Generated by Django 6.1.1 on 2026-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearchAgent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.IntegerField()),
                ("skill_type_id", models.IntegerField()),
                ("started_at", models.DateTimeField()),
                ("points_per_day", models.FloatField()),
                ("remainder_points", models.FloatField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_agents",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "agent_id")},
            },
        ),
    ]
