# Generated by Django 6.1.1 on 2026-10-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField()),
                ("type_id", models.IntegerField(db_index=True)),
                ("quantity", models.IntegerField()),
                ("location_id", models.BigIntegerField()),
                ("location_type", models.CharField(max_length=20)),
                ("location_flag", models.CharField(max_length=60)),
                ("is_singleton", models.BooleanField()),
                ("is_blueprint_copy", models.BooleanField(null=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("root_location_id", models.BigIntegerField(db_index=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "item_id")},
            },
        ),
    ]
