# Generated by Django 6.1.1 on 2026-10-07 08:39

import django.db.models.deletion
import django.utils.timezone
import evecsm.events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("discord", "Discord"),
                            ("slack", "Slack"),
                            ("json", "Json"),
                        ],
                        default="json",
                        max_length=10,
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("events", models.JSONField(blank=True, default=list)),
                (
                    "secret",
                    models.CharField(
                        default=evecsm.events.models.new_secret, max_length=64
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_status", models.IntegerField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                ("last_delivery_at", models.DateTimeField(blank=True, null=True)),
                ("failures", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("event", models.CharField(max_length=60)),
                ("status", models.IntegerField(null=True)),
                ("ok", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                (
                    "webhook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="events.webhook",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
