# Generated by Django 6.1.1 on 2026-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField()),
                ("type", models.CharField(max_length=20)),
                ("status", models.CharField(db_index=True, max_length=30)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("availability", models.CharField(max_length=20)),
                ("for_corporation", models.BooleanField(default=False)),
                ("issuer_id", models.BigIntegerField()),
                ("issuer_corporation_id", models.BigIntegerField()),
                ("assignee_id", models.BigIntegerField()),
                ("acceptor_id", models.BigIntegerField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "reward",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "collateral",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "buyout",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("volume", models.FloatField(null=True)),
                ("days_to_complete", models.IntegerField(null=True)),
                ("start_location_id", models.BigIntegerField(null=True)),
                ("end_location_id", models.BigIntegerField(null=True)),
                ("date_issued", models.DateTimeField(db_index=True)),
                ("date_expired", models.DateTimeField()),
                ("date_accepted", models.DateTimeField(null=True)),
                ("date_completed", models.DateTimeField(null=True)),
                ("items_fetched", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_issued"],
                "unique_together": {("character", "contract_id")},
            },
        ),
        migrations.CreateModel(
            name="ContractItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.BigIntegerField()),
                ("type_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("is_included", models.BooleanField()),
                ("is_singleton", models.BooleanField()),
                ("raw_quantity", models.IntegerField(null=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="contracts.contract",
                    ),
                ),
            ],
        ),
    ]
