# Generated by Django 6.1.1 on 2026-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="EVECSM", max_length=60)),
                ("tagline", models.CharField(blank=True, max_length=120)),
                ("accent", models.CharField(default="#22d3ee", max_length=7)),
                ("logo_url", models.URLField(blank=True)),
                ("setup_completed", models.BooleanField(default=False)),
                ("setup_token", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "verbose_name_plural": "site settings",
                "permissions": [
                    ("manage_site", "Can change site settings"),
                    ("manage_access", "Can manage states and groups"),
                    ("manage_modules", "Can enable and disable modules"),
                    ("view_members", "Can see the member list"),
                ],
            },
        ),
    ]
