# Generated by Django 6.1.1 on 2026-10-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "permissions": [
                    ("manage_site", "Can change site settings"),
                    ("manage_access", "Can manage states and groups"),
                    ("manage_plugins", "Can enable and disable modules"),
                    ("view_members", "Can see the member list"),
                    ("manage_api", "Can manage API keys and switch APIs on and off"),
                    ("view_logs", "Can view the audit, API request and service logs"),
                ],
                "verbose_name_plural": "site settings",
            },
        ),
    ]
