# Generated by Django 6.1.1 on 2026-10-07 10:36

from django.db import migrations, models


def rename_default_site(apps, schema_editor):
    """Sites still using the old default name take the new one; a name someone chose is left alone."""
    SiteSettings = apps.get_model("site", "SiteSettings")
    SiteSettings.objects.filter(name="EVECSM").update(name="EvE Conduit")


def undo(apps, schema_editor):
    SiteSettings = apps.get_model("site", "SiteSettings")
    SiteSettings.objects.filter(name="EvE Conduit").update(name="EVECSM")


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0003_alter_sitesettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitesettings",
            name="name",
            field=models.CharField(default="EvE Conduit", max_length=60),
        ),
        migrations.RunPython(rename_default_site, undo),
    ]
