# Generated by Django 6.1.2 on 2026-10-07 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0004_rename_to_eve_conduit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "permissions": [
                    ("manage_site", "Can change site settings"),
                    ("manage_access", "Can manage states and groups"),
                    ("manage_plugins", "Can enable and disable plugins"),
                    ("view_members", "Can see the member list"),
                    ("manage_api", "Can manage API keys and switch APIs on and off"),
                    ("view_logs", "Can view the audit, API request and service logs"),
                    ("view_health", "Can see server health (workers, queues, ESI)"),
                    ("impersonate_users", "Can sign in as another user to help them"),
                ],
                "verbose_name_plural": "site settings",
            },
        ),
    ]
