# Generated by Django 6.1.2 on 2026-10-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0005_plugin_permission_wording"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="start_page",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
