# Generated by Django 6.1.2 on 2026-10-07 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def find_owner(apps, schema_editor):
    """Existing sites: the owner is whoever claimed the setup code (from the audit log), else the first administrator."""
    SiteSettings = apps.get_model("site", "SiteSettings")
    User = apps.get_model("accounts", "User")
    AuditEvent = apps.get_model("audit", "AuditEvent")
    site = SiteSettings.objects.filter(pk=1).first()
    if site is None or site.owner_id:
        return
    claim = AuditEvent.objects.filter(action="setup.admin_claimed", actor_id__isnull=False).order_by("pk").first()
    owner = User.objects.filter(pk=claim.actor_id, is_superuser=True).first() if claim else None
    owner = owner or User.objects.filter(is_superuser=True).order_by("date_joined", "pk").first()
    if owner is not None:
        site.owner = owner
        site.save(update_fields=["owner"])


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0006_start_page"),
        ("audit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(find_owner, migrations.RunPython.noop),
    ]
