# Generated by Django 6.1.2 on 2026-10-07 21:14

from django.db import migrations, models


def land_on_home(apps, schema_editor):
    """Sites still on the old default (the dashboard) now open on the new landing page."""
    apps.get_model("site", "SiteSettings").objects.filter(start_page="").update(start_page="/home")


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0007_site_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="landing",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="sitesettings",
            name="start_page",
            field=models.CharField(blank=True, default="/home", max_length=200),
        ),
        migrations.RunPython(land_on_home, migrations.RunPython.noop),
    ]
