# Generated by Django 6.1.2 on 2026-10-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0008_landing_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="nav_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="nav_links_title",
            field=models.CharField(default="Links", max_length=40),
        ),
    ]
