# Generated by Django 6.1.1 on 2026-10-07 08:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_userpreferences"),
        ("eve", "0002_evename_marketprice"),
        ("sheet_killmails", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporationInfo",
            fields=[
                (
                    "corporation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="info",
                        serialize=False,
                        to="eve.evecorporation",
                    ),
                ),
                ("ceo_id", models.BigIntegerField(null=True)),
                ("creator_id", models.BigIntegerField(null=True)),
                ("date_founded", models.DateTimeField(null=True)),
                ("description", models.TextField(blank=True)),
                ("home_station_id", models.BigIntegerField(null=True)),
                ("member_count", models.PositiveIntegerField(null=True)),
                ("shares", models.BigIntegerField(null=True)),
                ("tax_rate", models.FloatField(null=True)),
                ("url", models.CharField(blank=True, max_length=300)),
                ("faction_id", models.IntegerField(null=True)),
                ("war_eligible", models.BooleanField(null=True)),
                ("hangar_divisions", models.JSONField(default=list)),
                ("wallet_divisions", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Starbase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starbase_id", models.BigIntegerField(unique=True)),
                ("type_id", models.IntegerField()),
                ("system_id", models.IntegerField()),
                ("moon_id", models.IntegerField(null=True)),
                ("state", models.CharField(blank=True, max_length=20)),
                ("onlined_since", models.DateTimeField(null=True)),
                ("reinforced_until", models.DateTimeField(null=True)),
                ("unanchor_at", models.DateTimeField(null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starbases",
                        to="eve.evecorporation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("structure_id", models.BigIntegerField(unique=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("type_id", models.IntegerField()),
                ("system_id", models.IntegerField()),
                ("profile_id", models.IntegerField(null=True)),
                ("state", models.CharField(max_length=40)),
                ("fuel_expires", models.DateTimeField(null=True)),
                ("state_timer_start", models.DateTimeField(null=True)),
                ("state_timer_end", models.DateTimeField(null=True)),
                ("unanchors_at", models.DateTimeField(null=True)),
                ("reinforce_hour", models.SmallIntegerField(null=True)),
                ("next_reinforce_hour", models.SmallIntegerField(null=True)),
                ("services", models.JSONField(default=list)),
                ("fuel_warned", models.BooleanField(default=False)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CorpAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.BigIntegerField()),
                ("type_id", models.IntegerField(db_index=True)),
                ("quantity", models.IntegerField()),
                ("location_id", models.BigIntegerField()),
                ("location_type", models.CharField(max_length=20)),
                ("location_flag", models.CharField(max_length=60)),
                ("is_singleton", models.BooleanField()),
                ("is_blueprint_copy", models.BooleanField(null=True)),
                ("name", models.CharField(blank=True, max_length=100)),
                ("root_location_id", models.BigIntegerField(db_index=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "unique_together": {("corporation", "item_id")},
            },
        ),
        migrations.CreateModel(
            name="CorpContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField()),
                ("type", models.CharField(max_length=20)),
                ("status", models.CharField(db_index=True, max_length=30)),
                ("availability", models.CharField(max_length=20)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("issuer_id", models.BigIntegerField()),
                ("assignee_id", models.BigIntegerField(null=True)),
                ("acceptor_id", models.BigIntegerField(null=True)),
                ("for_corporation", models.BooleanField(default=False)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                (
                    "reward",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                (
                    "collateral",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                ("volume", models.FloatField(null=True)),
                ("date_issued", models.DateTimeField(db_index=True)),
                ("date_expired", models.DateTimeField(null=True)),
                ("date_completed", models.DateTimeField(null=True)),
                ("start_location_id", models.BigIntegerField(null=True)),
                ("end_location_id", models.BigIntegerField(null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_issued"],
                "unique_together": {("corporation", "contract_id")},
            },
        ),
        migrations.CreateModel(
            name="CorpIndustryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.BigIntegerField()),
                ("installer_id", models.BigIntegerField()),
                ("activity_id", models.SmallIntegerField()),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("blueprint_type_id", models.IntegerField()),
                ("product_type_id", models.IntegerField(null=True)),
                ("runs", models.IntegerField()),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                ("facility_id", models.BigIntegerField()),
                ("location_id", models.BigIntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(db_index=True)),
                ("completed_date", models.DateTimeField(null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_jobs",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("corporation", "job_id")},
            },
        ),
        migrations.CreateModel(
            name="CorpJournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.SmallIntegerField()),
                ("ref_id", models.BigIntegerField()),
                ("date", models.DateTimeField(db_index=True)),
                ("ref_type", models.CharField(db_index=True, max_length=60)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("first_party_id", models.BigIntegerField(null=True)),
                ("second_party_id", models.BigIntegerField(null=True)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-ref_id"],
                "unique_together": {("corporation", "division", "ref_id")},
            },
        ),
        migrations.CreateModel(
            name="CorpMarketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.BigIntegerField()),
                ("type_id", models.IntegerField()),
                ("is_buy_order", models.BooleanField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=22)),
                ("volume_total", models.IntegerField()),
                ("volume_remain", models.IntegerField()),
                ("issued", models.DateTimeField()),
                ("issued_by", models.BigIntegerField(null=True)),
                ("duration", models.IntegerField()),
                ("location_id", models.BigIntegerField()),
                ("region_id", models.IntegerField()),
                ("wallet_division", models.SmallIntegerField(null=True)),
                (
                    "escrow",
                    models.DecimalField(decimal_places=2, max_digits=22, null=True),
                ),
                ("state", models.CharField(default="active", max_length=20)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_orders",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued"],
                "unique_together": {("corporation", "order_id")},
            },
        ),
        migrations.CreateModel(
            name="CorporationKillmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_loss", models.BooleanField()),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="killmails",
                        to="eve.evecorporation",
                    ),
                ),
                (
                    "killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporations",
                        to="sheet_killmails.killmail",
                    ),
                ),
            ],
            options={
                "unique_together": {("corporation", "killmail")},
            },
        ),
        migrations.CreateModel(
            name="CorporationMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("start_date", models.DateTimeField(null=True)),
                ("logon_date", models.DateTimeField(null=True)),
                ("logoff_date", models.DateTimeField(null=True)),
                ("location_id", models.BigIntegerField(null=True)),
                ("ship_type_id", models.IntegerField(null=True)),
                ("base_id", models.IntegerField(null=True)),
                ("roles", models.JSONField(default=list)),
                ("titles", models.JSONField(default=list)),
                ("tracked", models.BooleanField(default=False)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "unique_together": {("corporation", "character_id")},
            },
        ),
        migrations.CreateModel(
            name="CorpSyncStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("section", models.CharField(max_length=40)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("ok", "Ok"),
                            ("error", "Error"),
                            ("no_character", "No Character"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=300)),
                ("last_attempt", models.DateTimeField(blank=True, null=True)),
                ("last_success", models.DateTimeField(blank=True, null=True)),
                (
                    "next_due",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("failures", models.PositiveIntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.character",
                    ),
                ),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_statuses",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "corporation sync statuses",
                "permissions": [
                    ("view_own_corporation", "Can view their own corporation's sheet"),
                    (
                        "view_alliance_corporations",
                        "Can view the sheets of corporations in their alliance",
                    ),
                    ("view_all_corporations", "Can view every corporation's sheet"),
                    (
                        "view_corporation_wallets",
                        "Can view corporation finances (wallets, market, contracts)",
                    ),
                ],
                "unique_together": {("corporation", "section")},
            },
        ),
        migrations.CreateModel(
            name="CorpTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.SmallIntegerField()),
                ("transaction_id", models.BigIntegerField()),
                ("date", models.DateTimeField(db_index=True)),
                ("type_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=22)),
                ("is_buy", models.BooleanField()),
                ("client_id", models.BigIntegerField()),
                ("location_id", models.BigIntegerField()),
                ("journal_ref_id", models.BigIntegerField(null=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-transaction_id"],
                "unique_together": {("corporation", "division", "transaction_id")},
            },
        ),
        migrations.CreateModel(
            name="MiningObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observer_id", models.BigIntegerField()),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("recorded_corporation_id", models.BigIntegerField(null=True)),
                ("type_id", models.IntegerField()),
                ("quantity", models.BigIntegerField()),
                ("last_updated", models.DateField(db_index=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mining_observations",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    (
                        "corporation",
                        "observer_id",
                        "character_id",
                        "type_id",
                        "last_updated",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="MoonExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("structure_id", models.BigIntegerField()),
                ("moon_id", models.IntegerField()),
                ("extraction_start_time", models.DateTimeField()),
                ("chunk_arrival_time", models.DateTimeField()),
                ("natural_decay_time", models.DateTimeField()),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extractions",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["chunk_arrival_time"],
                "unique_together": {
                    ("corporation", "structure_id", "extraction_start_time")
                },
            },
        ),
        migrations.CreateModel(
            name="WalletDivision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("division", models.SmallIntegerField()),
                ("balance", models.DecimalField(decimal_places=2, max_digits=22)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "corporation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet_divisions",
                        to="eve.evecorporation",
                    ),
                ),
            ],
            options={
                "ordering": ["division"],
                "unique_together": {("corporation", "division")},
            },
        ),
    ]
