# Generated by Django 6.1.1 on 2026-10-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.BigIntegerField()),
                ("date", models.DateTimeField(db_index=True)),
                ("title", models.CharField(max_length=200)),
                ("importance", models.SmallIntegerField(default=0)),
                ("response", models.CharField(blank=True, max_length=20)),
                ("duration", models.IntegerField(null=True)),
                ("owner_name", models.CharField(blank=True, max_length=200)),
                ("owner_type", models.CharField(blank=True, max_length=20)),
                ("text", models.TextField(blank=True)),
                ("detail_fetched", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_events",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("character", "event_id")},
            },
        ),
    ]
