# Generated by Django 6.1.1 on 2026-10-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletBalance",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="wallet",
                        serialize=False,
                        to="accounts.character",
                    ),
                ),
                ("balance", models.DecimalField(decimal_places=2, max_digits=20)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref_id", models.BigIntegerField()),
                ("date", models.DateTimeField(db_index=True)),
                ("ref_type", models.CharField(db_index=True, max_length=60)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("description", models.CharField(blank=True, max_length=500)),
                ("reason", models.CharField(blank=True, max_length=500)),
                ("first_party_id", models.BigIntegerField(null=True)),
                ("second_party_id", models.BigIntegerField(null=True)),
                ("context_id", models.BigIntegerField(null=True)),
                ("context_id_type", models.CharField(blank=True, max_length=40)),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journal",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-ref_id"],
                "unique_together": {("character", "ref_id")},
            },
        ),
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.BigIntegerField()),
                ("date", models.DateTimeField(db_index=True)),
                ("type_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("is_buy", models.BooleanField()),
                ("is_personal", models.BooleanField(default=True)),
                ("client_id", models.BigIntegerField()),
                ("location_id", models.BigIntegerField()),
                ("journal_ref_id", models.BigIntegerField(null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-transaction_id"],
                "unique_together": {("character", "transaction_id")},
            },
        ),
    ]
