# Generated by Django 6.1.1 on 2026-10-07 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="preferences",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("system", "System"),
                            ("dark", "Dark"),
                            ("light", "Light"),
                        ],
                        default="dark",
                        max_length=10,
                    ),
                ),
                (
                    "density",
                    models.CharField(
                        choices=[
                            ("comfortable", "Comfortable"),
                            ("compact", "Compact"),
                        ],
                        default="comfortable",
                        max_length=12,
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                ("clock_24h", models.BooleanField(default=True)),
                ("reduce_motion", models.BooleanField(default=False)),
                ("text_scale", models.PositiveSmallIntegerField(default=0)),
                ("high_contrast", models.BooleanField(default=False)),
                ("muted_categories", models.JSONField(blank=True, default=list)),
                ("dashboard", models.JSONField(blank=True, default=dict)),
                ("modules", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
