# Generated by Django 6.1.2 on 2026-10-08 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userpreferences"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userpreferences",
            options={"verbose_name_plural": "user preferences"},
        ),
    ]
