# Generated by Django 6.1.2 on 2026-10-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_preferences_plural"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpreferences",
            name="theme",
            field=models.CharField(
                choices=[
                    ("system", "System"),
                    ("dark", "Dark"),
                    ("light", "Light"),
                    ("sakura", "Sakura"),
                    ("neotokyo", "Neo Tokyo"),
                ],
                default="dark",
                max_length=10,
            ),
        ),
    ]
