# Generated by Django 6.1.2 on 2026-10-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webhook",
            name="mention",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="webhook",
            name="mention_always",
            field=models.BooleanField(default=False),
        ),
    ]
