# Generated by Django 6.1.1 on 2026-10-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SkillSummary",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="skill_summary",
                        serialize=False,
                        to="accounts.character",
                    ),
                ),
                ("total_sp", models.BigIntegerField(default=0)),
                ("unallocated_sp", models.BigIntegerField(default=0)),
                ("charisma", models.IntegerField(null=True)),
                ("intelligence", models.IntegerField(null=True)),
                ("memory", models.IntegerField(null=True)),
                ("perception", models.IntegerField(null=True)),
                ("willpower", models.IntegerField(null=True)),
                ("bonus_remaps", models.IntegerField(null=True)),
                ("last_remap_date", models.DateTimeField(null=True)),
                ("remap_available_date", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CharacterSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_id", models.IntegerField(db_index=True)),
                ("active_level", models.PositiveSmallIntegerField()),
                ("trained_level", models.PositiveSmallIntegerField()),
                ("skillpoints", models.BigIntegerField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "skill_id")},
            },
        ),
        migrations.CreateModel(
            name="SkillQueueItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField()),
                ("skill_id", models.IntegerField()),
                ("finished_level", models.PositiveSmallIntegerField()),
                ("start_date", models.DateTimeField(null=True)),
                ("finish_date", models.DateTimeField(null=True)),
                ("training_start_sp", models.BigIntegerField(null=True)),
                ("level_start_sp", models.BigIntegerField(null=True)),
                ("level_end_sp", models.BigIntegerField(null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_queue",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("character", "position")},
            },
        ),
    ]
