# Generated by Django 6.1.1 on 2026-10-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_id", models.BigIntegerField()),
                ("contact_type", models.CharField(max_length=20)),
                ("standing", models.FloatField()),
                ("is_blocked", models.BooleanField(default=False)),
                ("is_watched", models.BooleanField(default=False)),
                ("labels", models.JSONField(default=list)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "contact_id")},
            },
        ),
    ]
