# Generated by Django 6.1.2 on 2026-10-07 21:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnoopEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "viewer_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("viewer_name", models.CharField(max_length=150)),
                ("impersonating", models.CharField(blank=True, max_length=150)),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("character_name", models.CharField(max_length=200)),
                (
                    "owner_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("owner_name", models.CharField(blank=True, max_length=150)),
                ("section", models.CharField(max_length=40)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["viewer_id", "character_id", "section", "at"],
                        name="audit_snoop_viewer__343f49_idx",
                    )
                ],
            },
        ),
    ]
