# Generated by Django 6.1.2 on 2026-10-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_snoopevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelog",
            name="plugin",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
    ]
