# Generated by Django 6.1.1 on 2026-10-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bloodline",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("race_id", models.IntegerField(null=True)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
