# Generated by Django 6.1.1 on 2026-10-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0002_bloodline_race"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanetSchematic",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("cycle_time", models.IntegerField(null=True)),
            ],
        ),
    ]
