# Generated by Django 6.1.1 on 2026-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndustryJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.BigIntegerField()),
                ("activity_id", models.SmallIntegerField()),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("blueprint_id", models.BigIntegerField()),
                ("blueprint_type_id", models.IntegerField()),
                ("product_type_id", models.IntegerField(null=True)),
                ("runs", models.IntegerField()),
                ("licensed_runs", models.IntegerField(null=True)),
                ("successful_runs", models.IntegerField(null=True)),
                ("probability", models.FloatField(null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("facility_id", models.BigIntegerField()),
                ("station_id", models.BigIntegerField()),
                ("output_location_id", models.BigIntegerField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(db_index=True)),
                ("pause_date", models.DateTimeField(null=True)),
                ("completed_date", models.DateTimeField(null=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_jobs",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("character", "job_id")},
            },
        ),
    ]
