# Generated by Django 6.1.2 on 2026-10-07 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="corpsyncstatus",
            options={
                "permissions": [
                    ("view_own_corporation", "Can view their own corporation's sheet"),
                    (
                        "view_alliance_corporations",
                        "Can view the sheets of corporations in their alliance",
                    ),
                    ("view_all_corporations", "Can view every corporation's sheet"),
                    (
                        "view_corporation_wallets",
                        "Can view corporation finances (wallets, market, contracts)",
                    ),
                    (
                        "refresh_corporations",
                        "Can refresh corporation data from ESI now (corporations they can view)",
                    ),
                ],
                "verbose_name_plural": "corporation sync statuses",
            },
        ),
    ]
