# Generated by Django 6.1.1 on 2026-10-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("published", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name_plural": "item categories",
            },
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("published", models.BooleanField(default=False)),
                ("volume", models.FloatField(null=True)),
                ("packaged_volume", models.FloatField(null=True)),
                ("capacity", models.FloatField(null=True)),
                ("mass", models.FloatField(null=True)),
                ("portion_size", models.IntegerField(default=1)),
                ("base_price", models.FloatField(null=True)),
                ("icon_id", models.IntegerField(null=True)),
                ("race_id", models.IntegerField(null=True)),
                ("tech_level", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MetaGroup",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="SdeVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("build_number", models.PositiveIntegerField(unique=True)),
                ("release_date", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-build_number"],
            },
        ),
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("published", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="groups",
                        to="sde.itemcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkillInfo",
            fields=[
                (
                    "type",
                    models.OneToOneField(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        related_name="skill_info",
                        serialize=False,
                        to="sde.itemtype",
                    ),
                ),
                ("rank", models.FloatField(default=1)),
                ("primary_attribute", models.CharField(blank=True, max_length=12)),
                ("secondary_attribute", models.CharField(blank=True, max_length=12)),
                ("required_skills", models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name="itemtype",
            name="group",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="types",
                to="sde.itemgroup",
            ),
        ),
        migrations.CreateModel(
            name="MarketGroup",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("has_types", models.BooleanField(default=False)),
                ("icon_id", models.IntegerField(null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="children",
                        to="sde.marketgroup",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="itemtype",
            name="market_group",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="types",
                to="sde.marketgroup",
            ),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="meta_group",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="types",
                to="sde.metagroup",
            ),
        ),
        migrations.CreateModel(
            name="Constellation",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "region",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="constellations",
                        to="sde.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolarSystem",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("security_status", models.FloatField(default=0)),
                ("security_class", models.CharField(blank=True, max_length=4)),
                (
                    "constellation",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="systems",
                        to="sde.constellation",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="systems",
                        to="sde.region",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("type_id", models.IntegerField()),
                ("owner_id", models.IntegerField(null=True)),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "solar_system",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="stations",
                        to="sde.solarsystem",
                    ),
                ),
            ],
        ),
    ]
