# Generated by Django 6.1.2 on 2026-10-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0003_planetschematic"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="fitting",
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="required_skills",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="sdeversion",
            name="schema",
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
