# Generated by Django 6.1.2 on 2026-10-10 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sde", "0004_fitting_and_requirements"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="compressed_type_id",
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.CreateModel(
            name="TypeMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_type_id", models.IntegerField()),
                ("quantity", models.IntegerField()),
                (
                    "type",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="materials",
                        to="sde.itemtype",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("type", "material_type_id"),
                        name="sde_type_material_unique",
                    )
                ],
            },
        ),
    ]
