# Generated by Django 6.1.1 on 2026-10-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mail_id", models.BigIntegerField()),
                ("sender_id", models.BigIntegerField(null=True)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("is_read", models.BooleanField(default=False)),
                ("labels", models.JSONField(default=list)),
                ("recipients", models.JSONField(default=list)),
                ("body", models.TextField(blank=True)),
                ("body_fetched", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("character", "mail_id")},
            },
        ),
        migrations.CreateModel(
            name="MailLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_id", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(blank=True, max_length=7)),
                ("unread", models.IntegerField(default=0)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mail_labels",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "label_id")},
            },
        ),
    ]
