# Generated by Django 6.1.1 on 2026-10-07 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("level", models.CharField(db_index=True, max_length=10)),
                ("logger", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("traceback", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=60)),
                ("summary", models.CharField(max_length=400)),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("api_key", "Api Key"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("actor_id", models.BigIntegerField(blank=True, null=True)),
                ("actor_name", models.CharField(blank=True, max_length=150)),
                ("target_type", models.CharField(blank=True, max_length=40)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("target_name", models.CharField(blank=True, max_length=200)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
                "indexes": [
                    models.Index(
                        fields=["actor_type", "actor_id"],
                        name="audit_audit_actor_t_6fa4ef_idx",
                    )
                ],
            },
        ),
    ]
