# Generated by Django 6.1.2 on 2026-10-07 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plugins", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PluginInstaller",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catalog", models.JSONField(blank=True, default=dict)),
                ("catalog_checked_at", models.DateTimeField(blank=True, null=True)),
                ("catalog_error", models.CharField(blank=True, max_length=300)),
                ("auto_update", models.JSONField(blank=True, default=list)),
                ("notified", models.JSONField(blank=True, default=dict)),
                ("job_id", models.CharField(blank=True, max_length=32)),
                (
                    "job_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("requested", "Requested"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("job_actions", models.JSONField(blank=True, default=list)),
                ("job_summary", models.CharField(blank=True, max_length=500)),
                ("job_automatic", models.BooleanField(default=False)),
                ("job_requested_at", models.DateTimeField(blank=True, null=True)),
                ("job_message", models.TextField(blank=True)),
                (
                    "job_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
