"""Regenerate backend/conduit/esi/rate_groups.py from ESI's OpenAPI spec.

    python scripts/esi-rate-groups.py 2026-08-18             # downloads the spec for that compatibility date
    python scripts/esi-rate-groups.py 2026-08-18 spec.json   # or reads a copy you already have

Run it whenever ESI_COMPATIBILITY_DATE is bumped.
"""

import json
import re
import sys
import urllib.request
from pathlib import Path

date = sys.argv[1]
if len(sys.argv) > 2:
    spec = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
else:
    url = f"https://esi.evetech.net/meta/openapi.json?compatibility_date={date}"
    request = urllib.request.Request(url, headers={"User-Agent": "EvE-Conduit/scripts (+https://github.com/EvE-Conduit/Eve-conduit)"})
    with urllib.request.urlopen(request, timeout=30) as resp:
        spec = json.load(resp)

groups: dict[str, str] = {}
limits: dict[str, str] = {}
for path, ops in spec["paths"].items():
    route = re.sub(r"\{[^}]+\}", "{n}", path)  # the client's _route() shape: /characters/{n}/wallet
    for op in ops.values():
        limit = op.get("x-rate-limit") if isinstance(op, dict) else None
        if not limit:
            continue
        if groups.setdefault(route, limit["group"]) != limit["group"]:
            sys.exit(f"{route} is in two rate-limit groups; the client keys pauses by route, so it needs changing")
        limits[limit["group"]] = f"{limit['max-tokens']}/{limit['window-size']}"  # same form as X-Ratelimit-Limit

lines = [
    f'"""ESI route -> rate-limit group, from the OpenAPI spec for compatibility date {date}.',
    "",
    "Generated by scripts/esi-rate-groups.py; don't edit by hand. Lets the client honour a group's pause",
    "before the first response has told it the group. Routes not listed only have the error limit.",
    '"""',
    "",
    "ROUTE_GROUPS = {",
    *(f'    "{route}": "{group}",' for route, group in sorted(groups.items())),
    "}",
    "",
    "#: Tokens per window for each group, as X-Ratelimit-Limit gives them (per character, or per IP for public routes).",
    "GROUP_LIMITS = {",
    *(f'    "{group}": "{limit}",' for group, limit in sorted(limits.items())),
    "}",
    "",
]
out = Path(__file__).resolve().parent.parent / "backend" / "conduit" / "esi" / "rate_groups.py"
out.write_text("\n".join(lines), encoding="utf-8")
print(f"{len(groups)} routes written to {out}")
