# Generated by Django 6.1.1 on 2026-10-06 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CharacterInfo",
            fields=[
                (
                    "character",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="info",
                        serialize=False,
                        to="accounts.character",
                    ),
                ),
                ("birthday", models.DateTimeField(null=True)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("race_id", models.IntegerField(null=True)),
                ("bloodline_id", models.IntegerField(null=True)),
                ("security_status", models.FloatField(null=True)),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("faction_id", models.IntegerField(null=True)),
                ("solar_system_id", models.IntegerField(null=True)),
                ("station_id", models.BigIntegerField(null=True)),
                ("structure_id", models.BigIntegerField(null=True)),
                ("ship_type_id", models.IntegerField(null=True)),
                ("ship_name", models.CharField(blank=True, max_length=100)),
                ("online", models.BooleanField(null=True)),
                ("last_login", models.DateTimeField(null=True)),
                ("last_logout", models.DateTimeField(null=True)),
                ("logins", models.IntegerField(null=True)),
                ("home_location_id", models.BigIntegerField(null=True)),
                ("last_clone_jump_date", models.DateTimeField(null=True)),
                ("implants", models.JSONField(default=list)),
                ("jump_clones", models.JSONField(default=list)),
                ("jump_fatigue_expires", models.DateTimeField(null=True)),
                ("last_jump_date", models.DateTimeField(null=True)),
                ("titles", models.JSONField(default=list)),
                ("roles", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CorporationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("record_id", models.IntegerField()),
                ("corporation_id", models.BigIntegerField()),
                ("start_date", models.DateTimeField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corporation_history",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
                "unique_together": {("character", "record_id")},
            },
        ),
    ]
