# Generated by Django 6.1.1 on 2026-10-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Killmail",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("hash", models.CharField(max_length=64)),
                ("time", models.DateTimeField(db_index=True)),
                ("solar_system_id", models.IntegerField()),
                ("victim_character_id", models.BigIntegerField(null=True)),
                ("victim_corporation_id", models.BigIntegerField(null=True)),
                ("victim_alliance_id", models.BigIntegerField(null=True)),
                ("victim_ship_type_id", models.IntegerField()),
                ("damage_taken", models.IntegerField()),
                ("attacker_count", models.IntegerField()),
                ("final_blow_character_id", models.BigIntegerField(null=True)),
                ("value", models.FloatField(default=0)),
                ("data", models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name="CharacterKillmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_loss", models.BooleanField()),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="killmails",
                        to="accounts.character",
                    ),
                ),
                (
                    "killmail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="involved",
                        to="sheet_killmails.killmail",
                    ),
                ),
            ],
            options={
                "unique_together": {("character", "killmail")},
            },
        ),
    ]
