# Generated by Django 6.1.2 on 2026-10-07 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UpdateState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("check_error", models.CharField(blank=True, max_length=300)),
                ("releases", models.JSONField(blank=True, default=list)),
                ("notified_version", models.CharField(blank=True, max_length=20)),
                (
                    "download_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("downloading", "Downloading"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("download_version", models.CharField(blank=True, max_length=20)),
                ("download_file", models.CharField(blank=True, max_length=120)),
                ("download_size", models.BigIntegerField(default=0)),
                ("download_received", models.BigIntegerField(default=0)),
                ("download_error", models.CharField(blank=True, max_length=300)),
                (
                    "install_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("requested", "Requested"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=12,
                    ),
                ),
                ("install_version", models.CharField(blank=True, max_length=20)),
                ("install_requested_at", models.DateTimeField(blank=True, null=True)),
                ("install_message", models.TextField(blank=True)),
                (
                    "install_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
