# Generated by Django 6.1.1 on 2026-10-07 08:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EsiCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("method", models.CharField(max_length=6)),
                ("route", models.CharField(db_index=True, max_length=200)),
                ("path", models.CharField(max_length=300)),
                ("query", models.CharField(blank=True, max_length=300)),
                (
                    "character_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("source", models.CharField(blank=True, db_index=True, max_length=80)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("ok", "Ok"),
                            ("not_modified", "Not Modified"),
                            ("error", "Error"),
                            ("rate_limited", "Rate Limited"),
                            ("network", "Network"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("error", models.CharField(blank=True, max_length=300)),
                ("error_limit_remain", models.SmallIntegerField(blank=True, null=True)),
                ("ratelimit_group", models.CharField(blank=True, max_length=80)),
                ("ratelimit_remaining", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
