# Generated by Django 6.1.1 on 2026-10-06 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("eve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=300)),
                ("color", models.CharField(default="#38bdf8", max_length=7)),
                (
                    "joinable",
                    models.BooleanField(
                        default=False, help_text="Users can join and leave freely"
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Not listed to users who are not members",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth.group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "priority",
                    models.IntegerField(
                        help_text="Higher wins when several states match", unique=True
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("color", models.CharField(default="#64748b", max_length=7)),
                (
                    "public",
                    models.BooleanField(default=False, help_text="Matches every user"),
                ),
                (
                    "member_alliances",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="eve.evealliance"
                    ),
                ),
            ],
            options={
                "ordering": ["-priority"],
            },
        ),
    ]
