# Generated by Django 6.1.1 on 2026-10-07 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def joinable_to_modes(apps, schema_editor):
    """Open groups stay open both ways; the others stay managed by admins (no leaving either)."""
    GroupProfile = apps.get_model("access", "GroupProfile")
    GroupProfile.objects.filter(joinable=True).update(join_mode="open", leave_mode="open")
    GroupProfile.objects.filter(joinable=False).update(join_mode="closed", leave_mode="closed")


class Migration(migrations.Migration):

    dependencies = [
        ("access", "0002_initial"),
        ("accounts", "0002_userpreferences"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceStatus",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="compliance",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("compliant", models.BooleanField(default=False)),
                ("problems", models.JSONField(blank=True, default=list)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("checked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name_plural": "compliance statuses",
                "permissions": [
                    (
                        "view_compliance",
                        "Can see which members' characters need attention",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="auto",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="auto_remove",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="grace_hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="join_mode",
            field=models.CharField(
                choices=[
                    ("open", "Anyone allowed can join"),
                    ("request", "Ask a group leader"),
                    ("closed", "Only leaders and admins add members"),
                ],
                default="closed",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="last_evaluated",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="leader_groups",
            field=models.ManyToManyField(blank=True, related_name="+", to="auth.group"),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="leaders",
            field=models.ManyToManyField(
                blank=True, related_name="led_groups", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="leave_mode",
            field=models.CharField(
                choices=[
                    ("open", "Members can leave"),
                    ("request", "Ask a group leader"),
                    ("closed", "Only leaders and admins remove members"),
                ],
                default="open",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="requirements",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="groupprofile",
            name="rules",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="AutoGroupGrace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "failing_since",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "group")},
            },
        ),
        migrations.CreateModel(
            name="GroupRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("join", "Join"), ("leave", "Leave")],
                        default="join",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=500)),
                ("response", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="auth.group",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("user", "group", "kind"),
                        name="one_pending_group_request",
                    )
                ],
            },
        ),
        migrations.RunPython(joinable_to_modes, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="groupprofile",
            name="joinable",
        ),
    ]
