# Generated by Django 6.1.1 on 2026-10-06 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.BigIntegerField()),
                ("type_id", models.IntegerField()),
                ("is_buy", models.BooleanField()),
                ("is_corporation", models.BooleanField(default=False)),
                ("price", models.DecimalField(decimal_places=2, max_digits=20)),
                ("volume_total", models.IntegerField()),
                ("volume_remain", models.IntegerField()),
                ("min_volume", models.IntegerField(null=True)),
                (
                    "escrow",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
                ("issued", models.DateTimeField()),
                ("duration", models.IntegerField()),
                ("location_id", models.BigIntegerField()),
                ("region_id", models.IntegerField()),
                ("range", models.CharField(max_length=20)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="market_orders",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued"],
                "unique_together": {("character", "order_id")},
            },
        ),
    ]
