# Generated by Django 6.1.1 on 2026-10-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveName",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=30)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MarketPrice",
            fields=[
                ("type_id", models.IntegerField(primary_key=True, serialize=False)),
                ("average_price", models.FloatField(null=True)),
                ("adjusted_price", models.FloatField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
