# Generated by Django 6.1.1 on 2026-10-06 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModuleState",
            fields=[
                (
                    "module_id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("installed_version", models.CharField(blank=True, max_length=40)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
