# Generated by Django 6.1.1 on 2026-10-06 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_id", models.BigIntegerField()),
                ("type", models.CharField(db_index=True, max_length=80)),
                ("sender_id", models.BigIntegerField()),
                ("sender_type", models.CharField(max_length=20)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("is_read", models.BooleanField(default=False)),
                ("text", models.TextField(blank=True)),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.character",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("character", "notification_id")},
            },
        ),
    ]
