# Generated by Django 6.1.1 on 2026-10-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site", "0002_alter_sitesettings_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sitesettings",
            options={
                "permissions": [
                    ("manage_site", "Can change site settings"),
                    ("manage_access", "Can manage states and groups"),
                    ("manage_modules", "Can enable and disable modules"),
                    ("view_members", "Can see the member list"),
                    ("manage_api", "Can manage API keys and switch APIs on and off"),
                    ("view_logs", "Can view the audit, API request and service logs"),
                    ("view_health", "Can see server health (workers, queues, ESI)"),
                    ("impersonate_users", "Can sign in as another user to help them"),
                ],
                "verbose_name_plural": "site settings",
            },
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_message",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="maintenance_mode",
            field=models.BooleanField(default=False),
        ),
    ]
